# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dutchsec test site (Lars)
email: lars.boelhouwers@dutchsec.com
description: > # this means to ignore newlines until "baseurl:"
  This is an testsite made for an assignment.
  This assignment was given to me by Dutchsec.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://larstds.github.io" # the base hostname & protocol for your site
github_username:  LarsTD

# Build settings
markdown: kramdown
